file-repository:
  dir: "vouchers"
  file-name: "list.txt"

spring:
  datasource:
    url: "jdbc:mysql://localhost/order_mgmt"
    username: "root"
    password: "0000"
    driver-class-name: com.mysql.cj.jdbc.Driver
